---
- name: Install updates
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common software
  apt:
    name: "{{ package_list }}"
    state: latest

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Change hostname in hosts-file
  lineinfile:
    path: "/etc/hosts"
    regexp: "^127.0.1.1"
    line: 127.0.1.1 {{ hostname }}
